### PR TITLE
modify https to http as default

### PR DESCRIPTION
**Pull request by davidtaylorjr**
This changes the default URL to use http: instead of https:

However, when you modify the settings json to use https (which is the default behavior) it will pull https from the server as normal.

No other functionality was changed in the patch fix.

This should allow all users to be able to use the extension no matter if they are behind a corporate firewall or not.

### CODE REVIEW

**Comment by Jakobud** [comment]
I can't tell what was changed in this.

**Comment by davidtaylorjr** [comment]
That's a good thing! :)

It's subtle.

extension.js

Line 13: change https to http

Line 29: change https to http

**Comment by Jakobud** [comment]
- According to the diff, every line in the code is different. So that's definitely a problem. Even from a best practice standpoint you shouldn't ever commit more than what has actually changed. If you change just 2 lines in code, stage and commit just those lines, not the entire file which may or may not have changed due to some auto-formatting thing on your end or maybe your editor converted all tabs to spaces or vice-versa, etc. If anything, it helps to look at a commit and see EXACTLY what changed. Not "every single line says it changed but really didn't".
- Line 29 has nothing to do with what protocol is used to access cdnjs.com's API. It's only for the generated urls. Also this setting is user configurable so you can change it there.

While I appreciate the attempt to fix the problem, I think I am going to need to reject this because this only solves a problem that exists for the users behind a proxy, which is a tiny minority. On top of that, https is highly preferred over http in almost all situations. I don't think changing the default to non-SSL is the proper solution just to solve the problem. After all, that is exactly why Node.js has a strict SSL true/false option at all. If someone suggested to the Node.js team to just remove the "strict-ssl" option and make everything http by default, they would get laughed at.

Anyways, the correct solution is to determine why the extension is ignoring VSCode's own strict SSL setting and fix the problem there. Unfortunately it means the extension is going to be partially broken for those behind a proxy in the meantime. I am sympathetic to your issue and wish this wasn't a problem for you but I feel strongly that this is the right direction.

I will update the issue when I get more direction from the VSCode dev team. Thanks,

**Comment by Jakobud** [comment]
One other comment, I noticed that `http://api.cdnjs.com` automatically redirects to `https://api.cdnjs.com` anyways. Did you test this commit? Because that redirect tells me that it still wouldn't work anyways as `http://api.cdnjs.com` isn't going to give any sort of JSON response.

**Comment by davidtaylorjr** [comment]
I'm not sure why the diff says everything changed, that's odd. However, I
understand your position. I'll just use my fork since it works for my
scenario.

**Comment by davidtaylorjr** [comment]
And yes, I tested the commit and it works perfectly inside of VS Code now.

**Pull request closed without merging**
